### ISSUE TITLE
armv7 architecture

### ISSUE THREAD

**Issue by dothebart** [sleepycat/arangodb_arch#1]
Hi, looks great. 
You can also enable armv7, which should compile and work.

**Comment by dothebart** [comment]
(its not all clear to me whether gyp is also a system dependency or whether V8 brings its own)

**Comment by sleepycat** [comment]
@dothebart Thanks for taking a look. 
I'll add it shortly.

**Comment by sleepycat** [comment]
Arm support enabled in e1a7ae82194e
